spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/payments?serverTimezone=America/New_York
      username: paymenttest
      password: secret

server:
  port: 8096

