spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/cif?serverTimezone=America/New_York
     username: cif_user
     password: secret

server:
  port: 8098
